/*
   This file was generated automatically by the Mojo IDE version B1.3.5.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module adder_18 (
    input [5:0] alufn,
    input [7:0] a,
    input [7:0] b,
    output reg [7:0] sum1,
    output reg z,
    output reg v,
    output reg n
  );
  
  
  
  reg [7:0] newsum;
  
  reg xb7;
  
  always @* begin
    
    case (alufn[0+0-:1])
      1'h0: begin
        newsum = a + b;
      end
      1'h1: begin
        newsum = a - b;
      end
      default: begin
        newsum = a + b;
      end
    endcase
    sum1 = newsum;
    xb7 = b[7+0-:1] ^ alufn[0+0-:1];
    n = newsum[7+0-:1];
    if (a - b == 8'h00) begin
      z = 1'h1;
    end else begin
      z = 1'h0;
    end
    v = (a[7+0-:1] & xb7 & (~newsum[7+0-:1])) | ((~a[7+0-:1]) & (~xb7) & newsum[7+0-:1]);
  end
endmodule
